services:

  db:
    image: postgres:16
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: inventory_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: .
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql+psycopg://inventory_user:inventory_pass@db:5432/inventory_db
      JWT_SECRET: change_me_super_secret
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 200
      APP_ROLE: api
      RUN_SEED: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_TIMEZONE: UTC
      DISABLE_AUTH_FOR_SWAGGER: true
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql+psycopg://inventory_user:inventory_pass@db:5432/inventory_db
      APP_ROLE: worker
      RUN_SEED: 0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_TIMEZONE: UTC
      CELERY_WORKER_CONCURRENCY: 2

  beat:
    build:
      context: .
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql+psycopg://inventory_user:inventory_pass@db:5432/inventory_db
      APP_ROLE: beat
      RUN_SEED: 0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_TIMEZONE: UTC

volumes:
  postgres_data:
